In [2]:
import pandas as pd

In [3]:
#import cleaned dataset
Nigeria_medical_error = pd.read_csv("../cleaned_data/cleaned_medical_error_records_Nigeria.csv")
Other_medical_error = pd.read_csv("../cleaned_data/cleaned_medical_error_records_Others.csv")

In [4]:
Nigeria_medical_error.head()

,patient_id,hospital_facility_type,state,country,reporting_staff_role,patient_age,patient_gender,error_type,error_subtype,department,severity_level,outcome,detection_method,contributing_factor,report_source,corrective_action
0,1,Tertiary Hospital,Kano,Nigeria,Nurse,43,Male,Medication Error,Omitted Dose,Pharmacy,Minor,Temporary Harm,Patient Complaint,System Error,Internal Hospital Log,Root Cause Analysis
1,2,General Hospital,Lagos,Nigeria,Nurse,59,Female,Documentation Error,Wrong Patient Chart,Orthopedics,Minor,No Harm,Electronic System Alert,Miscommunication,Internal Hospital Log,Staff Training
2,3,Teaching Hospital,FCT,Nigeria,Pharmacist,26,Female,Documentation Error,Illegible Order,Pharmacy,Moderate,Death,Electronic System Alert,Staff Shortage,Ministry Audit,Equipment Maintenance
3,4,Teaching Hospital,Imo,Nigeria,Nurse,37,Female,Surgical Mistake,Post-op Bleed,Pharmacy,Moderate,Temporary Harm,Electronic System Alert,Equipment Failure,Internal Hospital Log,Equipment Maintenance
4,5,Teaching Hospital,Edo,Nigeria,Doctor,0,Male,Diagnostic Error,Result Misinterpretation,Orthopedics,Minor,Death,Self-report,Fatigue,Internal Hospital Log,Staff Training

In [5]:
Other_medical_error.head()

,patient_id,hospital_facility_type,state,country,reporting_staff_role,patient_age,patient_gender,error_type,error_subtype,department,severity_level,outcome,detection_method,contributing_factor,report_source,corrective_action
0,1,General Hospital,Mbale,Tanzania,Pharmacist,1,Male,Device/Equipment Error,Calibration Error,Pharmacy,Minor,Permanent Harm,Audit,Fatigue,Ministry Audit,Staff Training
1,2,Teaching Hospital,Kampala,Kenya,Lab Scientist,40,Male,Transfusion Error,Over-transfusion,Pediatrics,Minor,Permanent Harm,Self-report,Staff Shortage,Internal Hospital Log,SOP Update
2,3,Specialist Hospital,Nairobi,Uganda,Lab Scientist,42,Female,Medication Error,Wrong Dose,Pharmacy,Severe,No Harm,Self-report,System Error,Ministry Audit,Process Redesign
3,4,Teaching Hospital,Dodoma,Uganda,Doctor,59,Male,Surgical Mistake,Retained Item,Maternity,Moderate,No Harm,Electronic System Alert,Training Gap,Patient Report,Process Redesign
4,5,General Hospital,Dar es Salaam,Uganda,Nurse,48,Male,Surgical Mistake,Retained Item,Outpatient,Minor,Permanent Harm,Audit,Fatigue,Internal Hospital Log,Digital Record Adoption

In [6]:
#Join dataframes
combined_medical_error = pd.concat([Nigeria_medical_error, Other_medical_error], ignore_index=True)
combined_medical_error.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 554 entries, 0 to 553
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   patient_id              554 non-null    int64
 1   hospital_facility_type  554 non-null    object
 2   state                   554 non-null    object
 3   country                 554 non-null    object
 4   reporting_staff_role    554 non-null    object
 5   patient_age             554 non-null    int64
 6   patient_gender          554 non-null    object
 7   error_type              554 non-null    object
 8   error_subtype           554 non-null    object
 9   department              554 non-null    object
 10  severity_level          554 non-null    object
 11  outcome                 554 non-null    object
 12  detection_method        554 non-null    object
 13  contributing_factor     554 non-null    object
 14  report_source           554 non-null    object
 15  corrective_action       554 non-null    object
dtypes: int64(2), object(14)
memory usage: 69.4+ KB

In [12]:
#distribution of medical error
count_error_type = combined_medical_error['error_type'].value_counts().sort_values(ascending=True)
#count_error_type.plot(kind='barh', title='Distribution of Medical Error Types', xlabel='Count of Error Type', ylabel='Error Types');

In [7]:
#combined_medical_error[['error_type', 'country']].value_counts().sort_values(ascending=True)
combined_medical_error.groupby('country')['error_type'].value_counts().unstack().fillna(0)

error_type,Device/Equipment Error,Diagnostic Error,Documentation Error,Infection Control Error,Medication Error,Surgical Mistake,Transfusion Error
country,,,,,,,
Kenya,7,18,8,4,37,18,4
Nigeria,17,42,37,18,111,41,11
Tanzania,8,8,8,9,26,18,5
Uganda,5,10,13,10,37,18,6

In [13]:
#Distribution by facilities
count_facility = combined_medical_error["hospital_facility_type"].value_counts().sort_values(ascending=True)
count_facility

hospital_facility_type
General Hospital       120
Tertiary Hospital      132
Teaching Hospital      146
Specialist Hospital    156
Name: count, dtype: int64

In [15]:
#Distribution by location
count_location = combined_medical_error["country"].value_counts().sort_values(ascending=True)
count_location

country
Tanzania     82
Kenya        96
Uganda       99
Nigeria     277
Name: count, dtype: int64

In [18]:
#export combined dataset 
combined_medical_error.to_csv("../cleaned_data/combined_medical_error_records.csv", index=False)